### ISSUE TITLE
Transmog Suggestion / Enchanting applying fix

### ISSUE THREAD

**Issue by Becide** [N3kas/AdvancedEnchantments#101]
Hey, mind adding a option where you can edit the [%LOREAMOUNT%] on the transmog? 
The colors and other stuff. https://gyazo.com/aed55e1879ab13ce72ed683046c83145

**Comment by Becide** [comment]
The enchantment applying glitch.
make it so if you hit the enchant limit on weapon/gear, you can still apply heroic enchantments to upgrade that specific enchant.

**Comment by N3kas** [comment]
Added & Fixed.
