### ISSUE TITLE
Tinkerer issues and feature ideas

### ISSUE THREAD

**Issue by ToxFTP** [N3kas/AdvancedEnchantments#102]
Issues:
  - When closing the tinkerer and you have items in there it doesn't cancel the trade and give back your items.
  - The bank notes that are given once you make a tinkerer trade it doesn't take it away

Features:
  - Sounds when using the exp/money vouchers from the tinkerer
  - A way to make custom items in a config you can give to a player through a command and can set all the info. Name, lore, enchants, amount, item type, etc..
  - Conditions that you can set in the gkits. Basically you can set if the item comes with a certain enchant and level then add another enchant.

**Comment by N3kas** [comment]
It appears to give items back, at least from my test ([http://n3.fyi/ae/tinkergiveback.gif](http://n3.fyi/ae/tinkergiveback.gif)).
Fixed the tinkerer money voucher issue.

Will add the sounds.
What kind of custom items?
I'll think about that.
