### ISSUE TITLE
Gkits having whitescrolls

### ISSUE THREAD

**Issue by aegood** [N3kas/AdvancedEnchantments#107]
https://pastebin.com/wmBxi4yd - gkit config <-
https://vimeo.com/user88734987/review/286374606/9661534b8e - Video in game <-

Some Gkit armour is being protected by an imaginary white scroll that shouldnt be there.
Some isnt.
No error in console

(video might take a couple of minutes to upload)

Tested on no Op or any permission account still happening

**Comment by N3kas** [comment]
This is a new mechanic, as explained in updates:
http://prntscr.com/kmhp3r

It can be disabled upon setting http://prntscr.com/kmhpi2 to false.
