### ISSUE TITLE
Experience Enchant Book

### ISSUE THREAD

**Issue by Terrifical** [N3kas/AdvancedEnchantments#108]
The experience enchant book from the pvpwars/pvpingmc premade setup gives you less XP when its suppose to give you more.

If I kill 10 blazes without the enchant I would get 8 XP levels, if I had the enchant I'd get 4

**Comment by N3kas** [comment]
When it comes to minecraft mobs dropping experience, it's random and can vary by quite a lot. From my testing it seems to be functioning fine.
