### ISSUE TITLE
No protect island from Askyblock

### ISSUE THREAD

**Issue by JavituRec** [N3kas/AdvancedEnchantments#11]
Hello,

The enchants exlposives and ghast break blocks to the other islands.

Server version 1.8.8
Advanceenchants version: last
Plugin Skyblock: Askyblock

**Comment by N3kas** [comment]
Will be fixed. thanks for reporting.

**Comment by JavituRec** [comment]
Add:

enchants not work: Inky, ravenous, virus and kevlar

**Comment by N3kas** [comment]
Okay I’ll inform the person who made them.
