### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by ozm8** [N3kas/AdvancedEnchantments#112]
Using the latest advanced enchantments with spigot 1.13 and its spamming this error:

https://pastebin.com/XZjxPbnv

**Comment by N3kas** [comment]
Could you post that enchantment here?

**Comment by ozm8** [comment]
sure: https://pastebin.com/tB4UMXEi

**Comment by N3kas** [comment]
Do you know the exact enchant or no? Also, when does it spam that?

**Comment by ozm8** [comment]
not sure exactly i just looked the log and seems to happen. its not constant spam though but when it happens seems to spam

**Comment by ozm8** [comment]
i'll try and replicate it give me a bit
