### ISSUE TITLE
TYPES of AE not working

### ISSUE THREAD

**Issue by Becide** [N3kas/AdvancedEnchantments#120]
divineimmolation:
  display: '%group-color%Divine Immolation'
  description: 'An intensive damage dealing enchantment that requires 5-15 souls upon use.'
  applies-to: 'Swords'
  type: 'ATTACK'
  group: 'FANTASY'
  applies:
    - ALL_SWORD
  levels:
    4:
      chance: 100
      souls: 5
      effects:
        - 'MESSAGE:&c&l** DIVINE IMMOLATION ** %victim%'
(More of this is sent to Pm's through discord, dont wanna leak how this enchant work)

Some tpyes like "Attack" does not work. Mostly enchants for swords.

**Comment by N3kas** [comment]
Fixed.
