### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by ecoterrorist** [N3kas/AdvancedEnchantments#123]
Randomization of vanilla enchantment levels in gkits, etc.

The fact that you can give items that have "random" enchantment levels with gkits is one of my favorite features in this plugin, and I would love to see the same added for the vanilla enchantments on my gkits items as well.

Second Idea:
It would be really cool if there was a flag/effect/whatever you could attach to an enchantment in enchantments.yml that completely blocked said enchantment from being removed from an item and converted to book form with a black scroll.

**Comment by N3kas** [comment]
Added!
