### ISSUE TITLE
Issues with transmog scroll and blocktrak

### ISSUE THREAD

**Issue by ecoterrorist** [N3kas/AdvancedEnchantments#125]
Blocktrak doesn't seem to work at all, it successfully puts the counter in the item lore, but the number never goes above 0.

Transmog scrolls break items that they are placed on, rendering them completely useless. Image below.
![screen shot 2018-09-09 at 7 19 41 pm](https://user-images.githubusercontent.com/42695513/45270062-6ccf7800-b466-11e8-824e-d21466ced963.png)

**Comment by N3kas** [comment]
Fixed!
