### ISSUE TITLE
Request: Better Apply able Items / Transmog Bug

### ISSUE THREAD

**Issue by Becide** [N3kas/AdvancedEnchantments#128]
https://gyazo.com/fed990636485d7de5c6d9b830bcee4a2
If possible can you make it so that when you apply a CE book it does not send back to the original slot if its stacked?
Make it work like the orbs when they are stacked like it just gets rid of 1 but you still have them on your curser and it just -1's 1

Transmogs in a stack that are placed on gear dont get removed
look at gif below to see the bug
https://gyazo.com/cdbf8940995d745efd7d2656c49eb9ab

**Comment by N3kas** [comment]
Added & Fixed!
