### ISSUE TITLE
/ae yml Parsing error on cosmic premade yml

### ISSUE THREAD

**Issue by Jezuuh** [N3kas/AdvancedEnchantments#13]
Selected the premade cosmic enchantment list reloaded the plugin and restarted teh server and there are still no enchants.

Looked inside the custom enchant folder and all the enchants are there.

Put the enchantments config file in an online YML parser and the last enchantment folder longshot I think it was, was entered in wrong.

After removing the enchantment the enchants work perfectly. Might want to fix this as some users might not know what is wrong or how to fix it.

**Comment by N3kas** [comment]
Okay, thanks.

**Comment by N3kas** [comment]
Fixed!
