### ISSUE TITLE
Add: ITEM SET BONUS

### ISSUE THREAD

**Issue by croderdai** [N3kas/AdvancedEnchantments#131]
When player equip item armor same name set.
Ex:
Link: https://forum.cosmicpvp.com/threads/supreme-armor-set-equipment-lootboxes-gift-cards-40-off.293905/

Lore ex:
SUPREME SET BONUS
Gears IV
No Fall Damage
No Food Loss
Deal +15% damage to all enemies
Enemies using bows deal an additional 10% damage to you.
+200% Clout (Fly Enabled for all ranks when not combat tagged)
(Requires all 4 supreme items.)​

**Comment by croderdai** [comment]
And
You can add edit message while apply enchant book requires enchant

**Comment by N3kas** [comment]
Messages have been added but sets are planned for future in a separate plugin.

**Comment by croderdai** [comment]
Add: Message Alchemist
