### ISSUE TITLE
Give dust

### ISSUE THREAD

**Issue by imhandmade** [N3kas/AdvancedEnchantments#133]
Players can still givedust to themselves even with no permissions.

I have set all the permissions to false except to actually enchanter, tinkerer, and alchemist.

**Comment by N3kas** [comment]
What command are they using?

**Comment by imhandmade** [comment]
it's /ae magicdust <dust_quality> <% it gives> <Player_name>
not givedust

**Comment by N3kas** [comment]
Will fix, thanks!
