### ISSUE TITLE
Improvments & Ideas & 1 Issue

### ISSUE THREAD

**Issue by dabou0** [N3kas/AdvancedEnchantments#134]
Add option to get the enchants from the enchantment table, and the chance of getting each, and each level, you wont be able to see the enchant you will get probaly, but you will receive according to the chance, you just need to enchant normally your item and according to the chance you might receive a custom enchant on it or no

for example

Lifesteal 

'1'
Chance: 15%
Level: 10

'2'
Chance: 15%
Level: 20

'3'
Chance: 10%
Level: 30 (so for example i would need to enchant the item at level 30, to have a 10% chance of getting it)

Add so you can combine items in the anvil, for example i put 2 Lifesteals swords in the anvil, so i would get lifesteal 3, it doesnt matter if the items are damage, the damage repairing will be regular (vanilla), it will just increase the cost, for example if putting 2 damaged sword together would have a xp cost, because of the enchantment increase (2 lifesteals II to 1 lifesteal III) it will increase this cost, each enchant should have a cost of beeing made for example, 

'1'
Chance: 15%
Level: 10

'2'
Chance: 15%
Level: 20
Anvil:2 xp

'3'
Chance: 10%
Level: 30 
Anvil:5 xp

if it ultrapasses the slots limit, it will randomly remove the enchants till it show the maximum enchantments slots allowed for that item, and the player must accept to get the item, if he takes on of the items and put back it will change the random choosen enchantment to be removed, also if one of the item has the slot increaser it will be passed to the new item, and would be nice to add to the lore how many enchantments are allowed on that item.

Thank you for your attention, hope those are added, i believe they would increase a lot in the plugin, and would be easier system of custom enchants for specific gamemode as for example a pvp server.

Also im having a error when trying to get slotincreaser item
https://pastebin.com/zM1xJyTf

Thank you again for your attention

**Comment by N3kas** [comment]
The error comes from a configuration mistake which was sorted in previous updates. I suggest you regenerate your config.yml to resolve this issue.

What goes for the suggestions, will definitely look into these, thank you!

**Comment by dabou0** [comment]
ty

**Comment by dabou0** [comment]
is there any way i can get cosmicpvp setup ? ty

**Comment by N3kas** [comment]
Yes, it comes default with plugin. 
I cannot add the enchantment table chances yet but I'll definitely consider this in future, thank you!

**Comment by dabou0** [comment]
ok, one more question arre you planing on adding the anvil system, so players would be able to combine 2 swords, or armours, it would be a great increase for the plugin thank you, and also i can't download cosmicpvp setup it says its not avaiable because of confusing players, but i would like to have it if possible, thank you again

**Comment by N3kas** [comment]
Cosmicpvp setup comes as primary setup right away with plugin, upon first launch you will start with it.

No plans for anvils yet but that idea is in the list of possible new additions.
