### ISSUE TITLE
Lag improvements / Optimization Suggestions / Bugs

### ISSUE THREAD

**Issue by Becide** [N3kas/AdvancedEnchantments#135]
**An idea that can possibly make trenching lag mitigated a bunch**
* Make it so whenever you use a specific mining enchant such as detonate or atomic detonate,
it does not drop the blocks on the floor or give them to you. This can prevent so much lag from trenching.

**Gkit Lagg Issues:**
* There needs to be more optimizations if possible for /gkit click events, previewing, obtaining, and cooldowns. The optimizations are perfect for servers around 40-80 players. But it needs to be efficient for 150-500 players.

**Bugs with the new AE update which is 4.4.0**
* Blackscrolls dont work (ex: https://gyazo.com/be27c2122a2ea95021d666eb923cb004)
* When doing /ae reload, it GLOBALLY RESETS ALL GKIT COOLDOWNS for everyone thats on the server or just everyone in general.
* Renametags dont work when chat is muted by /mutechat (litebans). I don't know if its possible to make them work when the chat is muted.

**Comment by N3kas** [comment]
All fixed.
