### ISSUE TITLE
Placeholder \n sometimes didnt work

### ISSUE THREAD

**Issue by Yhenko** [N3kas/AdvancedEnchantments#139]
Hi, sometimes the placeholder \n didnt work, what can i do? 

https://i.gyazo.com/42babf1610efb67250a91da27258f2e3.png
https://i.gyazo.com/07974dfdd07dc959a4a78563882364b0.png

**Comment by N3kas** [comment]
Use double quotes instead of single, as provided in example below.

Proper way:
`description: "This is first line,\nThis is second line!"`

Way not to do it:
`description: 'This is first line,\nThis is second line!'`
