### ISSUE TITLE
/ae premade, Choosing TreasureWars setup breaks the plugin.

### ISSUE THREAD

**Issue by Destructuctor** [N3kas/AdvancedEnchantments#14]
When I do /ae premade, and choose treasurewars everything finishes succsesfully (cant spell), But then when I do anything like /ae givebook /ae giveitem /ae admin, it all breaks for me, like in /ae admin When I click a book I get this error here: https://hastebin.com/ipuruvifem.vbs
Please help, thanks, 
EDIT: None of the other setups work either, /enchanter does not print an error or do anything, Tinkerer also does not work, again thanks for the help!

**Comment by N3kas** [comment]
I haven't had any issues myself with any of the set ups, I'll have a look at it though. Thanks for reporting!
