### ISSUE TITLE
Custom Item Issues

### ISSUE THREAD

**Issue by doitliketyler** [N3kas/AdvancedEnchantments#140]
Decided to regen the config and start from scratch because a lot of new stuff wasn't automatically added. After that was done noticed a few customizations weren't synced up. The transmog scroll and soul gem currently aren't pulling in custom item, name or lore. Could you fix these when you get a chance? Thanks so much.

**Comment by N3kas** [comment]
That's very weird, I'm aware that there were issues with config in last update. From what it looks like it's just simply some kind of a mistake in my cloud not syncing between two computers.

Will definitely take care of this today, sorry about it!
