### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by doitliketyler** [N3kas/AdvancedEnchantments#142]
Hey there. I've just updated with the last version released and I'm getting this startup error:

https://pastebin.com/0gGfctsP

Thoughts?

**Comment by N3kas** [comment]
Yes, did you regenerate your config? Its either missing a setting for item or not recognising an item on 1.13

**Comment by doitliketyler** [comment]
I literally started from scratch last night and it takes awhile to get everything customized so I'm not going to do it all over again. I really shouldn't have to. Could you please just tell me what changed so I can manually update it?

**Comment by doitliketyler** [comment]
Also, all of the customize-able items should really be in their own config file. Just a thought.

**Comment by N3kas** [comment]
All changes are automatically added. I just assumed you have incomplete config due to previous ticket. It is one of the custom item's material that is being not recognised. If you want you can post the config (or pm it) so I can look without obfuscated version to tell you more information.

**Comment by doitliketyler** [comment]
I've PM'd my config to you on Spigot.

**Comment by N3kas** [comment]
Resolved.
