### ISSUE TITLE
TP Drops & Silk touch (4.4.5)

### ISSUE THREAD

**Issue by xDacon** [N3kas/AdvancedEnchantments#144]
If you use a tp_drops enchantment (telepathy) and silk touch together, you will receive the block in your inventory, but the block won't break

there's no errors with this issue. Server testing on is paper 1.12.2, using AE 4.4.5

https://gyazo.com/259c4d7b5bfc4a289fb56e74d7b42fd4

**Comment by N3kas** [comment]
Fixed.
