### ISSUE TITLE
Sword Enchants aren't effecting players

### ISSUE THREAD

**Issue by Jezuuh** [N3kas/AdvancedEnchantments#15]
So im having some issues with this plugin. Im using the default config and just trying to use some of the enchants. 

It seems that enchants that effect the users and not yourself don't seem to work. Im not getting any error messages in the console which is weird.

But I've been testing the poison enchant specifically, set the chances to 100 so it is guaranteed to poison every hit just to test and it doesn't work.

Really not sure why this isn't working. 

Using Paper 1.8.8 if that helps.

**Comment by Jezuuh** [comment]
Also not convinced that armour enchants are effecting other players. Seems there is an issue with effecting the other player

**Comment by N3kas** [comment]
If you want it to activate always, remove the whole "chance" part of configuration. It's currently working for me, must be something configuration wise.

**Comment by Jezuuh** [comment]
They just currently aren’t effecting players though, I could hit one person 200 times and they aren’t getting effected. Surely that isn’t down to the chance? 

I’ll see if I can create some error messages to understand what is going on but it currently isn’t possible to effect someone with the chance: effect on

**Comment by N3kas** [comment]
Would you mind messaging me on Discord for instant replies, easier to resolve this issue that way. My discord is GC#0830.
