### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by Ricozaur** [N3kas/AdvancedEnchantments#150]
Hello there, i'd like to make a request which i'm really in need for to start up my server.
I really want a custom payment to be available so i can pay for the books in a custom economy.
It would be quite unfortunate for me if you don't want it added.

An example: I use heroes and heroes uses an API to interact with the exp bar (if i'm correct) so uses custom levels like (class) Warrior. Lvl1, or (class) Crafter. Lvl1. Let's say that crafter is a secondary class. So you have the Warrior (primary class) which only will increase to unlock skills, and Crafter to gain levels by killing, mining, etc., but losing lvl's (exp) by buying books as well. Like this:

      '2':
        item:
          type: STAINED_GLASS_PANE
          id: 0
          force-glow: false
        enchant-group: SIMPLE
        price: heroes admin exp (player) (class) -400 (<--exp)     (<---- The custom economy/command)
        name: '&f&lSimple Enchantment &7(Right Click)'
        lore:
        - '&7Examine to recieve a random'
        - '&fsimple &7enchantment book.'
        - ''
        - '&b&lCOST &f400 EXP'

Thank you for reading, i am really in need for this (i know you can use money, but that would be last resort for me).

**Comment by N3kas** [comment]
I'm quite open to adding new features, at least I believe so but this is something that wouldn't be used widely, I'm pretty sure you'd be the only one using it so it's not a mainstream feature I can spend time working on.

Another flaw with this is that using commands for price is ridicules considering I have no verification that user met command requirements and got something taken from them, this at the end would work as an free purchase.

The only way for this to be implemented is by having it privately done.

**Comment by N3kas** [comment]
Yes I can add click events. Would you mind PMing me on Discord link to the heroes plugin so I can take a better look? My discord is GC#0830.
