### ISSUE TITLE
Request: Blacksmith

### ISSUE THREAD

**Issue by reflezion** [N3kas/AdvancedEnchantments#158]
Maybe add a feature where in config their is
Blacksmith: Enable/Disable
If you dont know what blacksmith is, you combine 2 of the same books to make 1 book with a higher level

Example: Haste 1 + Haste 1 = Haste 2

**Comment by ZeddyOG** [comment]
This is already a thing within AE its called Alchemist. You can combine 2 of the same level book for 1 higher level or combine dust to gain a higher % dust.

It can also be Enabled/Disabled by setting http://prntscr.com/l2okok
