### ISSUE TITLE
Gkits Reduced Cooldown Permission

### ISSUE THREAD

**Issue by doitliketyler** [N3kas/AdvancedEnchantments#159]
Hey there. I was wondering if you would add a permission that would reduce the overall cooldowns on the gkits? For example something like ae.gkit.cooldown.[percent] so we could do something like ae.gkit.cooldown.50 that would reduce the cooldowns by 50% on all gkits. Thoughts?

**Comment by N3kas** [comment]
Possibly in the future with an update to GKits but not now.
