### ISSUE TITLE
[Request] Soul Gem

### ISSUE THREAD

**Issue by Skythal** [N3kas/AdvancedEnchantments#16]
Similar to how CosmicPvP souls work, would be nice to have the souls in a gem form instead of on an item.
Would allow trading and selling of gems between players. Would also work with any soul enchant no matter the item its on. Enchants that require souls to work would then need the gem to be activated (by right clicking the gem) and then the soul enchants could proc (using up some of the souls per proc on the soul gem)

**Comment by N3kas** [comment]
Amazing timing! Update with soul gems is coming out in ~30 minutes!
