### ISSUE TITLE
Mob Coins Hook

### ISSUE THREAD

**Issue by matthew-wiggins** [N3kas/AdvancedEnchantments#160]
Hey, I own a MobCoins plugin on spigot called PvPingMobCoins and was wondering if you can hook into it and make a type that when a mob coin is given from killing a mob it triggers it. Many users that have bought my plugin have asked for this feature to be added/supported for other enchants plugin, and since I recommend your everytime someone asks I believe it would be the best fit.

**Comment by N3kas** [comment]
'it triggers it'. What kind of support do you want me to add to it?

**Comment by ToxFTP** [comment]
In the API there is an event that happens when a player receives a mobcoins from killing a mob. Could you add a type that would hook into that event?

**Comment by N3kas** [comment]
What would be the use of this? I don't understand how could this be beneficial to have.

**Comment by ToxFTP** [comment]
It would serve the same concept as EXP:(amount) but like MOBCOIN:(amount)
