### ISSUE TITLE
Issue with ./ae list that disconnect me

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#161]
I found a HUGE PROBLEM:

08.10 05:07:18 [Server] INFO maxlehot1234 issued server command: /ae list
08.10 05:07:18 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 47533 bytes encoded, max 32767)
08.10 05:07:18 [Disconnect] User maxlehot1234 has disconnected, reason: Disconnected

Occured each time I do: ./ae list to get the list of all enchants....

Do I have too many enchants? Any way to increase this to prevent me to be kicked?

Of course, the config was great and no yaml issue are detected.

Thanks again and have a nice day/night

**Comment by maxlehot1234** [comment]
@N3kas And, any idea?

**Comment by N3kas** [comment]
Will be fixed with next update.

**Comment by N3kas** [comment]
Fixed.
