### ISSUE TITLE
[Feature] Wildcard for ./ae greset command

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#163]
Are you able to add a wildcard for this command? /ae greset <player> <gkit> instead of gkit name, I can put * to reset all gkits cooldown ?

That could be a nice addition to the plugin.

Thanks again GC

**Comment by N3kas** [comment]
Added.

**Comment by maxlehot1234** [comment]
How this work? Doesn't found the command in the ./ae command

**Comment by N3kas** [comment]
Instead of specifying a gkit in /ae greset just put *

**Comment by maxlehot1234** [comment]
Already try that and told me to check the ae help menu

I try:
./ae greset playername *
./ae greset playername **

Same thing



Envoyé par myMail pour iOS


jeudi 11 octobre 2018 08:58 -0400 de notifications@github.com  <notifications@github.com>:
