### ISSUE TITLE
[Feature] Implement a tier function

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#164]
Is it possible to add tiers ?

Maybe implement a level thing inside your plugin.

So players will be able to get items, weapons, armor, etc that are level 30, but if they are level 20, they can't use it, since they need to be level 30.

Maybe something like this:
![image](https://user-images.githubusercontent.com/5159244/46623600-210efd80-cafc-11e8-850b-34f71e1f2e38.png)

It can be hard to develop, but this will be an amazing feature to add into your plugin.

Thank you and have a nice day

**Comment by ZeddyOG** [comment]
AdvancedEnchantments is simply a custom enchantments (with kits) plugin and (in my opinion) shouldn't branch out to this. 

Although I do believe maybe a condition or effect that checks if the player has a permission or is at a certain XP level (Not exactly sure what "level" you are referring to here)

**Comment by maxlehot1234** [comment]
Maybe as an add on?

And for levels I means that player can get items by doing anything on the server: votes, keys, events, kill players, kill mobs, etc.

All player actions are count as a level.

Some swords, armor, bow, pick axe, axe, etc required level XXXXX to allow player to put enchant on it and allow enchants to be enabled.
If the players doesn't have the level for it, they can't equip it or use it.

If the player was level 20 and get a level 19 pick axe with some enchants on it he can use it without issue.

If the player was level 30 and get a level 34 sword, he need to be at level 34 to be able to use this sword

Some enchants will be activated at Level XXXXX
Maybe a true/false value to use the level system.



Not sure if it was possible to do.

If not, maybe I can ask a dev to do it, but not sure that it was possible to be hook into AE :(


let me know if it was something that can be done or as an addon maybe? 


Thanks again for your reply.

That could be AMAZING




mardi 9 octobre 2018 22:44 -0400 de notifications@github.com  <notifications@github.com>:

**Comment by N3kas** [comment]
This isn't something I think would be widely used so I will not add this. AE has an API which may allow certain functions to be added.
