### ISSUE TITLE
[Feature] Identifing Module

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#165]
Monsters can sometimes drop unidentified items. These items must be identified using a specific consumable in order to be used. Unidentified items have their stats completely hidden on the item lore.

![image](https://user-images.githubusercontent.com/5159244/46623670-5f0c2180-cafc-11e8-8ebb-c6be35b0c092.png)

Thanks again and for your information, I have a LOT of ideas for your plugin

**Comment by N3kas** [comment]
This is something for an RPG plugin and not for enchantments.
