### ISSUE TITLE
[Issue] Players can click their inventory to get books instead of the GUI

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#166]
I can click in my inventory to get enchant books instead of the gui :stuck_out_tongue: Maybe block the player click in their inventory bar ?

They CAN'T GLITCH book, they need to get the EXP/MONEY for it . I just report this here:
http://g.recordit.co/jBB60vhLWz.gif

Normal?

**Comment by N3kas** [comment]
Fixed.

**Comment by maxlehot1234** [comment]
@N3kas Not fix in 4.5.2 :P Just saying ;) Still buying thing from my inventory
