### ISSUE TITLE
[Issue] Mystery-dust name become mystery in-game ?

### ISSUE THREAD

**Issue by maxlehot1234** [N3kas/AdvancedEnchantments#167]
Is it normal that mystery-dust from the config.yml file was named mystery in-game?
![image](https://user-images.githubusercontent.com/5159244/46770789-db4e6280-ccbe-11e8-884d-334a69d9478c.png)

Thanks again GC

**Comment by N3kas** [comment]
Yes, it's a shorter name for it so you do not have to type out 'mystery-dust' and rather just put 'mystery'
