### ISSUE TITLE
Add Clickable Soul Gems and help with current souls

### ISSUE THREAD

**Issue by RedaBoi** [N3kas/AdvancedEnchantments#168]
I would love if you can add a right Clickable Soul gem option to the plugin , like on cosmic , when right clicked activates soul mode which then drains souls and activates soul enchants , also I'm having issues with the current soul gems as even if applied to an item , the enchants work but souls are not drained . -Thanks , we do have the premium version of the plugin.

**Comment by N3kas** [comment]
I'm aware that one enchant does not drain souls, will be fixed.
What goes for clickable souls, it's currently only available as an addon, if you are interested in it contact me on Discord - GC#0830
