### ISSUE TITLE
Holy Protection Scroll Issue

### ISSUE THREAD

**Issue by Kalasky** [N3kas/AdvancedEnchantments#169]
If you die with an item that has the Holy Protection scroll applied to it, you will keep the item upon death. But the original item that had the Holy Protection falls on the ground where you died, with the Holy Protection still on the item. This is a way for players to dupe items and it should not be falling on the floor.

**Comment by N3kas** [comment]
What minecraft version is this occouring on?

**Comment by Kalasky** [comment]
1.13.1

**Comment by Kalasky** [comment]
You should mark this as closed since this has been resolved, thank you!
