### ISSUE TITLE
FR: Ability to change a message (click for details)

### ISSUE THREAD

**Issue by ecoterrorist** [N3kas/AdvancedEnchantments#176]
I request that in a future update we are able to change/remove the message that is displayed in chat upon clicking one of the placeholder stained-glass items in the Alchemist window. I have renamed the Alchemist "Wizard" on my server, but cannot change the message to reflect that. An example of the name disparity is shown below.
https://www.dropbox.com/s/ksa04njde5jtd5t/ae1.mov?dl=0

**Comment by N3kas** [comment]
Added
