### ISSUE TITLE
Detonate Enchant Issue

### ISSUE THREAD

**Issue by Kalasky** [N3kas/AdvancedEnchantments#181]
Can the enchant Detonate on a silk pick apply silk to all the blocks broken rather than just the single block mined please.

**Comment by N3kas** [comment]
Do you have an example of this issue?

**Comment by Kalasky** [comment]
User had sild on the pickaxe with the Detonate enchant, but the only block that is silked is the single one mined, the rest of the 3x3 comes out as cobble/dirt/not silk.

**Comment by N3kas** [comment]
Install WorldGuard
