### ISSUE TITLE
Some bugs/issues

### ISSUE THREAD

**Issue by Sywo** [N3kas/AdvancedEnchantments#19]
I am using the version 3.2.1
1 Gkits doesn't work it wouldn't enchant normal minecraft enchant (like protection)
2 Inquisitive doesn't really work exp:10 is same as exp:100
3 Detonate and Autosmelt aren't working together it only smelt the block that is mined instead of the whole 3x3 area
4 If a player is holding an enchant with 'EFFECT_STATIC' they can right click an enderchest and get the effect without wearing the armor

Spigot ID https://www.spigotmc.org/members/sywo.475621/

**Comment by N3kas** [comment]
1st - fixed in 3.2.3.
2nd - fixed in 3.2.3.
3rd - mostly fixed in 3.2.3.
4th - fixed in 3.2.3.
