### ISSUE TITLE
4.8.0 Won't Enable On Server

### ISSUE THREAD

**Issue by UnrealisticBeing** [N3kas/AdvancedEnchantments#195]
Hey, I noticed there was an update released and so I tried testing it out- and it won't launch on my server.

I'm running BeerSpigot Premium, version 1.2 (CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT))

My list of plugins (13): PunishGUI, PermissionsEx, Vault, Multiverse-Core, MythicMobs, Essentials, EssentialsProtect, Parkour, LiteBans, EssentialsSpawn, Factions, AdvancedEnchantments, ChatControl

Error log when I boot up: https://hastebin.com/ixevudanad.md

Thanks, please get back to me soon!

**Comment by N3kas** [comment]
It's broken at the moment, will be fixed tomorrow. For the time being, you need WorldGuard to use it.
