### ISSUE TITLE
[REQUEST] Random Enchanted Gear

### ISSUE THREAD

**Issue by Splodgebox** [N3kas/AdvancedEnchantments#2]
I was wondering if it was possible to make a command that gives you an item with random enchants on it.
Something like **/ae givearmor <player> <diamond/iron/etc> <helmet/chestplate/etc> <group/all> <amountofenchants>**

_This would be an amazing feature to add as I can continue working on a project I had in mind._

**Comment by N3kas** [comment]
Will be added! Thank you.

This suggestion ticket will be kept open for user support until implemented as a feature.
