### ISSUE TITLE
Condition issue

### ISSUE THREAD

**Issue by Sywo** [N3kas/AdvancedEnchantments#21]
Plugin Version 3.2.4
I'm using the premade version only tried oxygenate on the lasted version but I've tried almost every enchant that has "condition" and none of them are working. 
Error for oxygenate on console : https://pastebin.com/Z0FR7SVB

**Comment by N3kas** [comment]
This was an issue when no factions plugin was presented in the server. Will roll out a fix today in an update, thanks for reporting!
