### ISSUE TITLE
Some bug

### ISSUE THREAD

**Issue by Sywo** [N3kas/AdvancedEnchantments#22]
Version 3.2.4
Using premade version
After removing a custom enchant using black scroll it still says there isn't any free slots
Silktouch is bugged with telepathy custom enchant (When I mine a diamond block it gave me 2 instead of 1 diamond block)
If a player is holding an enchant with 'EFFECT_STATIC' they can right click an anvil and get the effect without wearing the armor

**Comment by N3kas** [comment]
Thanks, fixed.
