### ISSUE TITLE
You can get potion effects from Effect_Static items without wearing the item

### ISSUE THREAD

**Issue by Samfrog** [N3kas/AdvancedEnchantments#28]
Using the latest version of the plugin, regular spigot, and game version 1.12.2. It happens on my test server with consistent 19.8-20 tps and ~49ms ping. No console errors. As far as config, it is default with only 1 or 2 changes in the custom commands section (and those are only me enabling or disabling things). I just got the plugin recently so havent changed much of anything.

I noticed that in survival mode, with items that give static effects, if you very very quickly spam click an item 2 to 3 times depending on if it is equipped or not, the effect will be applied even though you do not have the item equipped.

The sequence of events would be like this:
**Unequipped item:** Drag the item to its appropriate slot (chest for chestplate), click three times in rapid succession (equip, unequip, apply effect) and the effect is applied without the armour. This does not need to be inhumanly fast or anything, but it will not work if you do it leisurely either. It appears that the first click equips it and applies the effect, the second click unequips it and removes the effect, and the third click for whatever reason, if it is quick enough, will not equip the item, but will apply the effect. 

For an equipped item, the sequence is the same, but remove the first step (so you only click it twice).

For tools, this will work if you use the slot selected in your hotbar. So if your hotbar has slot 3 selected, doing one of those sequences (depending on if that item was already in your hotbar or not) will allow you to get the potion effect without holding the item.

You can do this multiple times and stack effects, so you could end up with someone having, say, overload (more hearts), obisidnashield, waterbreathing and haste 3 without having any of those items equipped. You can also equip other armour (with potentially different effects) and it will not remove the glitched potion effects.

**Comment by N3kas** [comment]
The issue with this is - there’s no official API that handles armor wearing, taking it off and putting it on. So, we use what everyone else has to - armorequipevent api. It may just be visual glitch, but I’ll make sure to check it out, could be caused by something small.

**Comment by Samfrog** [comment]
I did check to make sure it wasn't just a visual glitch (i.e. doing this with aquatic will still allow infinite water breathing etc.)
Hopefully you can figure something out, but from what you said that sounds pretty unfortunate. Either way, thanks so much for the quick reply and saying you'd take a look at it! Hoping for the best 😄

**Comment by N3kas** [comment]
Has been fixed.
