### ISSUE TITLE
High Timings?

### ISSUE THREAD

**Issue by TasmanianNoob** [N3kas/AdvancedEnchantments#29]
Hello, I was testing around on my server and checked my timings and your plugin with the PlayerInteractEvent was fairly high not sure why might be my fault but anyway
(AdvancedEnchantments::Event: n.a.l.c (PlayerInteractEvent)count(2)  total(31.48% 0.017s, 34.83% of tick)avg(8.71ms per - 17.42ms/2.00 per tick))

Taken from these timings https://timings.aikar.co/?id=bca9059bada843109eb28b9e592a198b

**Comment by TasmanianNoob** [comment]
Timings seem to be really weird there tho

**Comment by N3kas** [comment]
Do you have any enchantments with RIGHT_CLICK enchantment type?

**Comment by TasmanianNoob** [comment]
nope

**Comment by N3kas** [comment]
Open another ticket if this issue persists, I have done a few changes to upcoming version.
