### ISSUE TITLE
Blackscrolls "1,2"

### ISSUE THREAD

**Issue by ShadeyWolf294** [N3kas/AdvancedEnchantments#33]
Heya,
Either I messed up somewhere in the configuration, or this is a genuine bug. Whenever someone adds a black scroll to an item, it sends a message in global chat just the numbers, "1" and "2".

Any ideas?

![](https://cdn.discordapp.com/attachments/421447113575104516/458337884424896553/d833d7c88dd3ef3dfa9750d1b179181f.png)

**Comment by N3kas** [comment]
It's left over debug messages, will be fixed in the update, thank you!
