### ISSUE TITLE
Self-Destruct isn't working

### ISSUE THREAD

**Issue by ShadeyWolf294** [N3kas/AdvancedEnchantments#36]
Heya,
I know you may already know similar to this issue due to another ticket that was made previously, but I would just like to inform you that the Self-Destruct enchantment doesn't work very well (if at all).

It does not generate any errors, it's just the default conditions given to the enchantment don't seem to fire it off, if you know what I mean? The condition given to it is:
```yaml
condition: "%victim health% > 3 : %stop%"
```
And we've tested it on my server, but no matter how many times a player is killed, even with the chance set to 100, it doesn't spawn any TNT (which is what it is supposed to do). I've tried fiddling around with the conditions, but I can't find a way to make it work.

Any ideas?

**Comment by N3kas** [comment]
I've tested it myself and can confirm it works, was your health lower than 1.5 hearts? (3 = 1.5 hearts, 20 = 10 hearts aka full health)
