### ISSUE TITLE
enchant limit perm

### ISSUE THREAD

**Issue by Devillion** [N3kas/AdvancedEnchantments#38]
I have been using the "ae.limit.<count>" ever since it was released, however it doesn't seem to be working now.

Did you change anything with this? In my config I have the default value set to 5, but I allow more enchants using that perm for some ranks. It's just not working now, even though it used to work perfect.

**Comment by N3kas** [comment]
I tested this and it works, if you wish PM me on Discord/in discord discussions channel with a follow-up question.
