### ISSUE TITLE
Max custom enchants

### ISSUE THREAD

**Issue by Devillion** [N3kas/AdvancedEnchantments#41]
We've been using the max custom enchants permissions ever since you released it for different ranks. It has worked great, however players are reporting that it's not working and on my tests I have confirmed that it doesn't work.

We have it set to 6 and 7 max enchants using permissions depending on the players rank, however they can only do up to 5 that is set in the config. (it used to work finde, but now it only lets them do up to 5 max)

**Comment by N3kas** [comment]
Configuration will override permissions.

**Comment by Devillion** [comment]
how do I fix this? The way I have it is the way you told me to originally do it in your discord channel.
