### ISSUE TITLE
Self-Destruct NPE

### ISSUE THREAD

**Issue by GhotiMayo** [N3kas/AdvancedEnchantments#43]
The effects self-destruct enchantment do not happen. Instead, I get a null pointer in console. I'm currently testing it on level 3, which I have set to a 100% chance, and nothing occurs.

My self-destruct settings and the console error: [https://hastebin.com/togoyaweya.vbs](url)

**Comment by N3kas** [comment]
What AE version are you running?

**Comment by GhotiMayo** [comment]
The error occurred while using version 3.5.3. I just tested the enchantment again on the new 3.5.4 and while the null pointer is gone, the effect does not work still, as nothing seems to happen. Same setup otherwise.

**Comment by N3kas** [comment]
The piece of configuration you posted is outdated, try updating to latest then deleting enchantments.yml and restarting.
