### ISSUE TITLE
GKit Error when trying to give armor or tools

### ISSUE THREAD

**Issue by Stealthisaur9** [N3kas/AdvancedEnchantments#50]
`> [23:12:57 INFO]: AdvancedEnchantments caught an error with an action involving inventories
> [23:12:57 WARN]: java.lang.NullPointerException
> [23:12:57 WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68)
> [23:12:57 WARN]: at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46)
> [23:12:57 WARN]: at n3kas.ae.gkits.a.a(a.java)
> [23:12:57 WARN]: at n3kas.ae.gkits.e.a(e.java)
> [23:12:57 WARN]: at n3kas.ae.globallisteners.b.a(b.java)
> [23:12:57 WARN]: at sun.reflect.GeneratedMethodAccessor389.invoke(Unknown Source)
> [23:12:57 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [23:12:57 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [23:12:57 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> [23:12:57 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [23:12:57 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [23:12:57 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> [23:12:57 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [23:12:57 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [23:12:57 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [23:12:57 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [23:12:57 WARN]: at java.lang.Thread.run(Thread.java:748)`

Kit:
`  explorer:
    hide: false
    slot: 0
    delay: 172800
    display:
      no-permission:
        material: STAINED_GLASS_PANE
        data: 14
        force-glow: false
        name: '&c{gkit}'
        lore:
        - '&7&lSTATUS &cNot unlocked'
        - '&cYou haven''t unlocked this kit yet!'
      cooldown:
        material: STAINED_GLASS_PANE
        data: 4
        name: '&e{gkit}'
        force-glow: false
        lore:
        - '&7&lSTATUS &eON COOLDOWN'
        - '&c{cooldown}&f left until you can use this gkit.'
      available:
        material: STAINED_GLASS_PANE
        data: 5
        name: '&a{gkit}'
        force-glow: false
        lore:
        - '&7&lSTATUS &aAVAILABLE'
        - '&cYou can use this kit now.'
    permission: gkits.explorer
    content:
      '1':
        material: IRON_SWORD
        data: 0
        amount: 1
        name: '&7&lEXPLORER SWORD'
        lore:
          - '&7For those just starting out.'
        enchants:
          - sharpness:1
      '2':
        material: IRON_HELMET
        data: 0
        amount: 1
        name: '&7&lEXPLORER HELMET'
        lore:
          - '&7For those just starting out.'
        enchants:
          - protection:1
      '3':
        material: IRON_CHESTPLATE
        data: 0
        amount: 1
        name: '&7&lEXPLORER CHESTPLATE'
        lore:
          - '&7For those just starting out.'
        enchants:
          - protection:1
      '4':
        material: IRON_LEGGINGS
        data: 0
        amount: 1
        name: '&7&lEXPLORER LEGGINGS'
        lore:
          - '&7For those just starting out.'
        enchants:
          - protection:1
      '5':
        material: IRON_BOOTS
        data: 0
        amount: 1
        name: '&7&lEXPLORER BOOTS'
        lore:
          - '&7For those just starting out.'
        enchants:
          - protection:1
      '6':
        material: BOW
        data: 0
        amount: 1
        name: '&7&lEXPLORER BOW'
        lore:
          - '&7For those just starting out.'
        enchants:
          - power:1
      '7':
        command: 'give %player% arrow 32'
      '8':
        command: 'give %player% 322 32'
      '9':
        command: 'give %player% obsidian 32'
      '10':
        command: 'give %player% tnt 32'
      '11':
        command: 'give %player% oak 32'
      '12':
        material: IRON_PICKAXE
        data: 0
        amount: 1
        name: '&7&lEXPLORER PICKAXE'
        lore:
          - '&7For those just starting out.'
        enchants:
          - efficiency:1
      '13':
        material: IRON_AXE
        data: 0
        amount: 1
        name: '&7&lEXPLORER AXE'
        lore:
          - '&7For those just starting out.'
      '14':
        material: IRON_SHOVEL
        data: 0
        amount: 1
        name: '&7&lEXPLORER SHOVEL'
        lore:
          - '&7For those just starting out.'
      '15':
        command: 'give %player% steak 16'`

**Comment by N3kas** [comment]
Use pastebin.com when posting configuration, from what you've posted I cannot understand anything. This is certainly a configuration issue and the most needed part of report is scrambled.

**Comment by Stealthisaur9** [comment]
My bad.
https://paste.pydis.com/iciciwirub.py
