### ISSUE TITLE
Detonate enchant bug is back :/

### ISSUE THREAD

**Issue by OpvpYT** [N3kas/AdvancedEnchantments#51]
I just break outside my region but the blocks of the region are break because it's a 3x3 zone, the pickaxe isn't mining in the region, but the enchants affect the region.

For example, if I break in wilderness, the warzone limit will be destroyed too.

**Comment by N3kas** [comment]
You might have /f bypass (/f admin) enabled on yourself. I tested the effect and it seems to be functioning fine.
