### ISSUE TITLE
Detonate and Experience enchant issue

### ISSUE THREAD

**Issue by lizzardboy912** [N3kas/AdvancedEnchantments#58]
When you have Detonate on a pickaxe and you try to break a 3x3x3 area in the wilderness the CE does not work. If you take that CE into a claimed land area you own the CE will work and it will break a 3x3x3 area. Also, with the Experience CE when you break a block that will give you XP it doesn't multiply it, it just gives you normal XP.

**Comment by N3kas** [comment]
What factions plugin are you using?

**Comment by Devillion** [comment]
massive core

**Comment by N3kas** [comment]
Experience enchantment is working - I just tested it. It adds experience when mining.
Other issue with trenching will be fixed.
