### ISSUE TITLE
/ae giverandombook doesnt work

### ISSUE THREAD

**Issue by Garfnarg** [N3kas/AdvancedEnchantments#60]
![image](https://user-images.githubusercontent.com/28577752/43498205-7f4fc5b8-950b-11e8-8891-d5e8b4ce31fb.png)
When I try doing /ae giverandombook Garfnarg legendary it says An internal error occered while attempting to perform this command... I put a picture of the console when doing this command.

**Comment by N3kas** [comment]
Since 'LEGENDARY' group is set in CAPS (as seen in groups.yml), it will be in CAPS when using the command. Use '/ae giverandombook Garfnarg LEGENDARY 1' next time.
