### ISSUE TITLE
BUG WITH ENCHANTS

### ISSUE THREAD

**Issue by shika258** [N3kas/AdvancedEnchantments#62]
Hi, it's really important

[RAVENOUS & IMPLANTS] don't work, when are are full food, you lose all your food when you use this enchant
i use 'ADD_FOOD:1'

[OVERLOAD]
you lose all your boost heal on combat sometimes

[GUARDIANS]
when player are in pvp and the golem die, they freeze and become invisible
video:
https://www.youtube.com/watch?v=OTweTXeOlyg&feature=youtu.be

[STORMCALLER]
sometimes when the lightning fall, on the attacker, if the victim is next to the attacker, the victime take the lightning damage sometimes
https://www.youtube.com/watch?v=OTweTXeOlyg&feature=youtu.be

[BLACK-SCROLL]
don't work

could you fix that quickly pls.
these bugs completely breaks the game.

**Comment by N3kas** [comment]
All of these have been fixed! Thank you for reporting.
