### ISSUE TITLE
Repeating Type

### ISSUE THREAD

**Issue by ShadeyWolf294** [N3kas/AdvancedEnchantments#65]
Thank you for responding to my ticket earlier, I'm either utterly dumb, or the "repeating" type doesn't work. I copied and pasted the exact example from your wiki and nothing happened. Instead, it sent other players message who had that enchantment. Any help?

**Comment by N3kas** [comment]
Did you use same enchant as provided in wiki?

**Comment by N3kas** [comment]
Confirmed it works.
