### ISSUE TITLE
my command enchantments no longer work

### ISSUE THREAD

**Issue by ozm8** [N3kas/AdvancedEnchantments#66]
Updated the advanced enchantments to the latest and I am using spigot 1.13. I had to command enchantments which makes an item unbreakable but it no longer works.

Here is how I have my enchantments configured, it used to work:

https://pastebin.com/enpnrZXW

**Comment by N3kas** [comment]
I don't think this would have worked even before as 'RIGHT_CLICK' never had '%attacker name%' - but for today's update this will work (added %victim name% & %attacker name% (same names)) to RIGHT_CLICK)
