### ISSUE TITLE
Experience enchant error

### ISSUE THREAD

**Issue by Yhenko** [N3kas/AdvancedEnchantments#67]
https://hastebin.com/aredixusum.cs

1.12.2 paperspigot, latest AdvancedEnchantments

**Comment by N3kas** [comment]
That's actually not related to experience enchantment, I will look into this though! Thanks.

**Comment by Yhenko** [comment]
Well, the enchant Experience didnt work anyway xD

**Comment by N3kas** [comment]
It's clearly working - I just tested it. It adds experience randomly when mining, exactly what it's supposed to do.
