### ISSUE TITLE
Support for Kingdoms+ and PlaceholderAPI.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#68]
Please add support for Kingdoms+ plugin (https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-12-2.11833/). And PAPI placeholders in Conditions will be really awesome.

**Comment by N3kas** [comment]
Will be added.

**Comment by N3kas** [comment]
Added support for Kingdoms+ in next update. PAPI placeholder support will be added in near future.
