### ISSUE TITLE
Lore Problem

### ISSUE THREAD

**Issue by vhjbdhjvbff** [N3kas/AdvancedEnchantments#7]
The custom enchants comes after the lore! Is there a way you could add priority to enchant lore to come first.. here's the problem!
![image](https://user-images.githubusercontent.com/13048300/39401087-45e0f4ca-4b35-11e8-9763-de5118af2a1e.png)
This is the default Gkit Sword!

**Comment by N3kas** [comment]
Currently the problem with that is if I change it, all items that add text in lore (e.g. whitescroll) will be lost in enchantments, so this is the way lore is handled now. I’ll add a setting to change that.
