### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#71]
How about abillity to check for certain enchantments on armor and items in hands?
Like: 
condition: '%victim has enchantment NAME offhand% : %continue%' 
condition: '%victim has enchantment NAME mainhand% : %continue%' 
condition: '%victim has enchantment NAME boots% : %continue%' 
and etc.

It can be used to create sets.

**Comment by N3kas** [comment]
Right now I will only add condition to check enchantment in main hand.
