### ISSUE TITLE
Gkits still not working for me

### ISSUE THREAD

**Issue by aegood** [N3kas/AdvancedEnchantments#72]
Error Log

07.08 18:28:31 [Server] INFO Aegood issued server command: /gkits
07.08 18:28:31 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to AdvancedEnchantments v4.0.06
07.08 18:28:31 [Server] INFO org.bukkit.event.EventException
07.08 18:28:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
07.08 18:28:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
07.08 18:28:31 [Server] INFO Caused by: java.lang.NullPointerException
07.08 18:28:31 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO at n3kas.ae.gkits.g.a(g.java) ~[?:?]
07.08 18:28:31 [Server] INFO at n3kas.ae.commands.a.a(a.java) ~[?:?]
07.08 18:28:31 [Server] INFO at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
07.08 18:28:31 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
07.08 18:28:31 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
07.08 18:28:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
07.08 18:28:31 [Server] INFO ... 16 more

Gkit Config
gkits-enabled: true

inventory:
  # Size of inventory
  # * Determine size of GKits inventory (1 row = 9 slots, max 6 rows)
  size: 2
  # Name of inventory
  # * Change the name of GKits inventory
  name: '&eG-Kits'
  # Custom inventory commnad
  # * Create a handy command to open GKits inventory
  custom-command: /gkits
  sounds:
    # Inventory opening sound
    # * Sound is played on inventory open via comamnd
    inventory-open: CLICK
    # Usage of kit sound
    # * Sound played upon the use of any of the Available kits
    kit-use: LEVEL_UP
    # These are 1.8 sounds, if your server version is 1.9 or higher, please use different sounds.
    # Invalid sounds will not spam console with errors, they will just not play.
# Let players preview GKits by right-clicking on any gkit (permission: gkit.preview)
preview:
  enabled: true
  inventory:
    # Biggest the inventory can be, set to "AUTO" if you want inventory size to be set depending on gkit content amount.
    # (1 row = 9 slots, max 6 rows)
    max-size: 4
    # If there is any free slots in preview inventory, should they be filled with selected block?
    fill-blanks: false
    material: STAINED_GLASS_PANE
    data: 15
# ((this adds custom enchantments support, you may give random level of custom enchantments, eg: "&fSpeed %1-3%" adding in lore))
messages:
  # Placeholders Available:
  # * {gkit} - Name of GKit
  # * {cooldown} - Cooldown of GKit
  cooldown: '&c&l(!) &cYou cannot use this kit yet, kit &c{gkit}&c is On cooldown &c({cooldown})'
  no-perm: '&c&l(!) &cYou don''t have permissions to use &c{gkit}&c kit.'
  used-kit: '&c&l(!) &cYou have used kit &c{gkit}.'
kits:
  # Kits may have some unique configuration, here are examples:
  #  * you may give random level of custom enchantments, eg: "speed:%1-3%"
  #  * add chance for an enchantment to not be added, eg: "!25!:speed:1"; 25% chance for the enchantment to not be added to item.
  god:
    slot: 0
    delay: 6000
    display:
      no-permission:
        material: STAINED_GLASS_PANE
        data: 14
        force-glow: false
        name: '&c{gkit}'
        lore:
        - '&7&lSTATUS &cNot unlocked'
        - '&cYou haven''t unlocked this kit yet!'
      cooldown:
        material: STAINED_GLASS_PANE
        data: 4
        name: '&e{gkit}'
        force-glow: false
        lore:
        - '&7&lSTATUS &eON COOLDOWN'
        - '&c{cooldown}&f left until you can use this gkit.'
      available:
        material: STAINED_GLASS_PANE
        data: 5
        name: '&a{gkit}'
        force-glow: false
        lore:
        - '&7&lSTATUS &aAVAILABLE'
        - '&cYou can use this kit now.'
    permission: gkits.god
    content:
      '1':
        material: DIAMOND_SWORD
        data: 0
        amount: 1
        name: '&c&lGOD SWORD'
        lore:
         - '&7Sword for the greatest warriors'
        advanced-enchantments:
         - "poison:%1-3%"
        enchants:
          - sharpness:5
          - unbreaking:3
      '2':
        material: GOLD_HELMET
        data: 0
        amount: 1
        name: '&6&lKING HELMET'
        lore:
         - '&7Helmet for kings'
        advanced-enchantments:
         - "glowing:1"
        enchants:
          - protection:4
          - unbreaking:3
      '3':
        command: 'tell %player% You can add commands as items for gkits!'
        enchants: 
          - protection:4
          - unbreaking:3
  enchanter:
    slot: 17
    delay: 210000
    display:
      no-permission:
        material: DIAMOND
        data: 0
        force-glow: false
        name: '&e&n{gkit}&r &7Kit'
        lore:
        - '&7Create the &7&ngodset&7 you'
        - '&7always wanted with this gkit.'
        - '&r'
        - '&e&lSTATUS: &7Not unlocked'
    cooldown: 
        material: DIAMOND
        data: 0
        force-glow: false
        name: '&e&n{gkit}&r &7Kit'
        lore:
        - '&7Create the &7&ngodset&7 you'
        - '&7always wanted with this gkit.'
        - '&r'
        - '&e&lSTATUS: &7On cooldown &7&o({cooldown})&r'
    Available:
        material: DIAMOND
        data: 0
        force-glow: false
        name: '&e&n{gkit}&r &7Kit'
        lore:
        - '&7Create the &7&ngodset&7 you'
        - '&7always wanted with this gkit.'
        - '&r'
        - '&e&lSTATUS: &7Available'
    permission: gkits.enchanter
    content:
    '1':
    command: 'ae giveitem %player% renametag 1'
    '2':
    command: 'ae givercbook CURSED %player% 10'
    '3':
    command: 'ae givercbook FORGOTTEN %player% 7'
    '4':
    command: 'ae givercbook FORSAKEN %player% 5'  

I have no idea why its not working. tried every thing i can think of

**Comment by N3kas** [comment]
Use pastebin.com to post your gkits.yml configuration
