### ISSUE TITLE
DAMAGE type.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#74]
Please add type for any type of damage that player gets.
Also read this: https://ibb.co/hPsqVp

**Comment by N3kas** [comment]
Sadly 'DAMAGE' enchant type cannot be added as it would very badly interfere with all other enchant types and would be a hit for performance.
That seems to be way off right away. It has enchant type of 'BOW' but is applied to chestplates (only bows allowed for 'BOW').

**Comment by En0tS** [comment]
How I can realize this enchantment?
