### ISSUE TITLE
Issue with enchantment book lore

### ISSUE THREAD

**Issue by Enrave** [N3kas/AdvancedEnchantments#77]
Hey,

I customized my enchantment books to look like this: https://gyazo.com/e9ee3f8349612fd0b5db554b3de40a89

However, the enchantment does not appear to display it's color on the lore. Here is a snippet from the config:

  name: '&bEnchantment Shard'
  lore:
  - ''
  - '&fDrag and drop onto an item to'
  - '&fapply this enchantment shard!'
  - ''
  - '%enchant% %level%'
  - '&d%applies% Enchantment'
  - ''
  - '&aSuccess Rate: %success%%'
  - '&cFailure Rate: %destroy%%'
  - ''
  - '&e&nDrag and Drop to Enchant'

If you could fix this, or point me in the correct direction, that would be great! Thank you!

**Comment by N3kas** [comment]
Will fix this.

**Comment by N3kas** [comment]
Fixed.
