### ISSUE TITLE
Some effects not working in 1.13

### ISSUE THREAD

**Issue by BHPirkle** [N3kas/AdvancedEnchantments#81]
These are tested using the default enchantments (Cosmic ones I guess). I couldn't test the PVP ones, and I could only test a handful since I gotta run my server.

Working:
- Springs
- Haste
- Glowing
- Anti Gravity

Not Working:
- Auto Smelt
- Telepathy
- Experience
- Oxygenate
- Epicness
- Reforged

Sorry I couldn't test too many!

**Comment by MamaBeau** [comment]
I can confirm on these too.
