### ISSUE TITLE
Tinkerer Issue

### ISSUE THREAD

**Issue by Enrave** [N3kas/AdvancedEnchantments#83]
Hey,

I can't seem to get the lores for the tinkerer.yml file working. Here is my configuration for the 'agree' button:

    agree:
      type: STAINED_GLASS_PANE
      id: 14
      name: '&aConfirm Trade'
      lore:
      - ''
      - '&fConfirm your trade with the'
      - '&ftinkerer to scrap your items!'
      - ''
      - '&e&nClick to Confirm'

Yet in-game, it looks like this: https://gyazo.com/16ea3e2c860cc0e85965b97f05f4b578

I don't know if this is an issue, or if I'm doing something totally wrong. Any help is appreciated!

**Comment by Enrave** [comment]
I wanted to add that over the last few minutes or so, I've been messing around with the file to see if I could find a way to make it work. 

I found that if you use the lore for the 'placeholder-items' item, it'll display for the 'agree' button. Since I have the 'placeholder-items' item lore disabled, I believe it's conflicting with the 'agree' button's lore.

Here's a few gifs that show what I mean:
https://gyazo.com/b59cc173e5457e36e570eb848b9df6aa
https://gyazo.com/e6e0ee03bfa1d7bea2c73f26776ece08

**Comment by N3kas** [comment]
Yup I assumed so, thanks :) If i am able to get home by today Ill get this fixed

**Comment by N3kas** [comment]
Fixed.
