### ISSUE TITLE
REPEATING type issue.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#84]
I tried to create enchantment with this type and I did not succeed.
Then I have tryed your example (from https://github.com/N3kas/AdvancedEnchantments/wiki/%C3%86-Repeating-Enchantments-(timed) ) and it don't works too.

**Comment by ZeddyOG** [comment]
If you can include your attempt at the enchantment so we can better help if it is a configuration issue.

**Comment by En0tS** [comment]
I already included link to not working example for this type.

**Comment by N3kas** [comment]
Testing on 1.8.9 and it works. What minecraft version are you using?

**Comment by En0tS** [comment]
1.12.2

**Comment by N3kas** [comment]
Fixed.
