### ISSUE TITLE
DEFENSE_BOW still don't works.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#86]
1.12.2, ae 4.1.1:
![123](https://user-images.githubusercontent.com/36606833/44179886-2191a600-a102-11e8-91f6-d66bf0f11510.jpg)

[AdvancedEnchantments] Failed to find e-type '[DEFENSE_BOW]' for enchantment 'magnetism'

**Comment by N3kas** [comment]
Fixed.
