### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ZeddyOG** [N3kas/AdvancedEnchantments#88]
https://pastebin.com/FJQWaUxj

**Comment by N3kas** [comment]
NEGATE_DAMAGE has been fixed.
At the moment guards cannot be renamed.
STEAL_MONEY works (sends a message in chat to victim when money is stolen).
BREAK should be used with 'SWING' enchant type (has %block type% condition).
DEFENSE_BOW has been fixed.
Fixed IGNORE_ARMOR_DAMAGE.
Fixed IGNORE_ARMOR.
