### ISSUE TITLE
/AdvancedEnchantments

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#93]
Commands broken by latest update, I get this when I try /ae /ae reload /ae give and etc.
![123](https://user-images.githubusercontent.com/36606833/44294448-ef1daf80-a29f-11e8-9fda-d0e645d8e833.jpg)

UP: Everything worked after installing WorldGuard.

**Comment by N3kas** [comment]
How will it work if its having issues with loading on your server, related to wg issue
