### ISSUE TITLE
IGNORE_ARMOR

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#95]
IGNORE_ARMOR steel doesn't do more damage than normal item without it.

**Comment by N3kas** [comment]
Post the enchantment you're using it with - my environment provided normal results.

**Comment by En0tS** [comment]
also tested on ae 4.1.4, same result

**Comment by N3kas** [comment]
Alright. I'll check this out again.

**Comment by N3kas** [comment]
Alright my code was reverted back to previous without a fix, now it's for sure fixed. Thanks for reporting!
